[theme]
primaryColor = "#0F766E"
backgroundColor = "#F8F8F8"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#282827"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200
